Repository grouparoo/app-examples, pull requests merged in 2021-02, with the labels that each got.

#103 Grouparoo V0.2.0
  Dockerfile
  package-lock.json
  package.json
Labels: enhancement

#107 Tag updates with core's version
  .github/workflows/update.yml
Labels: dependencies, enhancement

#108 Remove references to SCHEDULER env var
  .env.example
  .github/workflows/test.yml
  Dockerfile
  Procfile
  docker-compose.published.yml
  docker-compose.yml
  kube/grouparoo-web.yml
  kube/grouparoo-worker.yml
Labels: enhancement

#124 manually apply git tag
  .github/workflows/update.yml
Labels: bug
